apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - image: docker.io/lukaszziobro89/nd_microservice:0.0.2
        name: test-app
        env:
          - name: DEMO_GREETING
            value: "Hello from the environment"
          - name: DEMO_FAREWELL
            value: "Such a sweet sorrow2"
          - name: ARGOCD_APP_NAME
            value: ${ARGOCD_APP_NAME}
  directory:
    jsonnet:
      extVars:
        - name: app
          value: '${ARGOCD_APP_NAME}'
      tlas:
        - name: ns
          value: '${ARGOCD_APP_NAMESPACE}'
# destination:
  # server: 'https://kubernetes.default.svc'
  # namespace: default
        