apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - image: docker.io/lukaszziobro89/nd_microservice:0.0.2
        env:
          - name: DEMO_GREETING
            value: "Hello from the environment"
          - name: DEMO_FAREWELL
            value: "Such a sweet sorrow"
          - name: ARGOCD_APP_NAME
            value: ${ARGOCD_APP_NAME}
        name: test-app
        ports:
        - containerPort: 5000
