apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - image: docker.io/lukaszziobro89/nd_microservice:0.0.1
        name: test-app
        ports:
        - containerPort: 5000
